class PetProfile {
  String dogName;
  String breed;
  String ageCategory; // "Puppy", "Adult", "Senior"
  double weight;
  String weightUnit; // "lbs" or "kg"

  PetProfile({
    required this.dogName,
    required this.breed,
    required this.ageCategory,
    required this.weight,
    this.weightUnit = 'lbs',
  });
}

// Common dog breeds list
const List<String> dogBreeds = [
  'Affenpinscher',
  'Afghan Hound',
  'Airedale Terrier',
  'Akita',
  'Alaskan Malamute',
  'American Cocker Spaniel',
  'American Foxhound',
  'American Pit Bull Terrier',
  'American Staffordshire Terrier',
  'American Water Spaniel',
  'Anatolian Shepherd',
  'Appenzeller Sennenhund',
  'Australian Cattle Dog',
  'Australian Shepherd',
  'Australian Terrier',
  'Austrian Pinscher',
  'Azawakh',
  'Baghdadi Dog',
  'Basenji',
  'Basset Hound',
  'Bavarian Mountain Hound',
  'Beagle',
  'Bearded Collie',
  'Beauceron',
  'Bedlington Terrier',
  'Belgian Malinois',
  'Belgian Sheepdog',
  'Belgian Tervuren',
  'Bernese Mountain Dog',
  'Bichon Frise',
  'Billy',
  'Biewer Terrier',
  'Black and Tan Coonhound',
  'Black Russian Terrier',
  'Bloodhound',
  'Bluetick Coonhound',
  'Bobtail',
  'Boerboel',
  'Boglen Terrier',
  'Bolognese',
  'Bombay',
  'Bone Mouth Bulldog',
  'Border Collie',
  'Border Terrier',
  'Borzoi',
  'Boston Terrier',
  'Bouvier des Flandres',
  'Boxer',
  'Boykin Spaniel',
  'Braque d\'Auvergne',
  'Braque du Bourbonnais',
  'Brazilian Terrier',
  'Breton Spaniel',
  'Briard',
  'Briquet Griffon Vendéen',
  'Brittany',
  'Brittany Spaniel',
  'Broholmer',
  'Brussels Griffon',
  'Bruxellois',
  'Bucharest Sheepdog',
  'Buckingham Spaniel',
  'Buffy Griffon',
  'Bull Mastiff',
  'Bull Terrier',
  'Bulldog',
  'Bullmastiff',
  'Bullterrier Staffordshire',
  'Cabbage Roll Dog',
  'Cairn Terrier',
  'Cambodian Razorback',
  'Campo Fino',
  'Can de Palleiro',
  'Canaan Dog',
  'Canadian Eskimo Dog',
  'Cane Corso',
  'Canis Panther',
  'Cão da Serra da Estrela',
  'Cao de Agua',
  'Cao de Castro Laboreiro',
  'Cao Fila De Sao Miguel',
  'Cape Hunting Dog',
  'Cardigan Welsh Corgi',
  'Catahoula',
  'Catahoula Leopard Dog',
  'Catalan Sheepdog',
  'Caucasian Ovcharka',
  'Cesky Fousek',
  'Cesky Terrier',
  'Charbonneau',
  'Chartreux',
  'Chesapeake Bay Retriever',
  'Chestnut',
  'Chihuahua',
  'Chinese Chongqing Dog',
  'Chinese Crested',
  'Chinese Crested Dog',
  'Chinese Shar-Pei',
  'Chongqing',
  'Chow Chow',
  'Chow Chow',
  'Chucho',
  'Chug',
  'Cinnamon',
  'Circa',
  'Circassian Sheepdog',
  'Cirnechi dell\'Etna',
  'Cirneco dell\'Etna',
  'Clumber Spaniel',
  'Cock-a-Poo',
  'Cockapoo',
  'Cocker Spaniel',
  'Colby Pitbull',
  'Cold Water Dogs',
  'Colle Barbato',
  'Collie',
  'Collie Nose',
  'Colombian Mastiff',
  'Coloquintida',
  'Comondor',
  'Connemara Sheepdog',
  'Cordoba Fighting Dog',
  'Corgidor',
  'Coridor',
  'Cornelian Spaniel',
  'Cornish Pixie',
  'Cornish Squirrel Dog',
  'Cornwall Spaniel',
  'Corrientes',
  'Coton de Tulear',
  'Cotulla Mastiff',
  'Coubertin',
  'Cow Dog',
  'Crabier',
  'Crabier Creek Duck Dog',
  'Crested German Shepherd',
  'Crested German Shepherd Dog',
  'Crested German Shepherd Mix',
  'Crestat Rat Dog',
  'Cresteds',
  'Cretan Hound',
  'Crete Sheepdog',
  'Croatian Sheepdog',
  'Crocus',
  'Cromfoohunt',
  'Cross Breed',
  'Crusader',
  'Cuban Mastiff',
  'Cuddle',
  'Cuddly',
  'Cumberland Sheepdog',
  'Cumberland Spaniel',
  'Cumhound',
  'Cummer',
  'Cummerskull',
  'Curly Coated Retriever',
  'Curly-Coated Retriever',
  'Currahee',
  'Currawong',
  'Currichound',
  'Curry',
  'Currying Cur',
  'Curtal Dog',
  'Curtisax Spaniel',
  'Curuca',
  'Curuca Shepherd',
  'Curved Dog',
  'Cusack',
  'Cushing Terrier',
  'Cushion Spaniel',
  'Cusichona',
  'Cusichona Peruvian',
  'Cusichona Sato',
  'Cusichong',
  'Cusichongha',
  'Cusichongha Mixed',
  'Cusichongi',
  'Cusichongi Mixed',
  'Cusichongium',
  'Cusichongium Mixed',
  'Cusichongium Peruvian',
  'Cusichora',
  'Cusichora Mixed',
  'Cusichora Peruvian',
  'Cusichoran Sato',
  'Cusichores',
  'Cusichores Mixed',
  'Cusichores Peruvian',
  'Cusichores Sato',
  'Cusichoriensis',
  'Cusichoriensis Mixed',
  'Cusichoriensis Peruvian',
  'Cusichoriensis Sato',
  'Cusicho Sato',
  'Cusichona Dog',
  'Cusichona Dog Mixed',
  'Cusichona Dog Peruvian',
  'Cusichona Dog Sato',
  'Cusick Hound',
  'Cusick Setter',
  'Cupid Hound',
  'Cur',
  'Curaca',
  'Curacies Mastiff',
  'Cur Dog',
  'Cur Dogs',
  'Curds',
  'Cure',
  'Cured Cur',
  'Curele',
  'Curele Hound',
  'Curele Mastiff',
  'Cureles',
  'Cureles Hound',
  'Cureles Mastiff',
  'Cureles Retrieve',
  'Cureles Retriever',
  'Cureles Setter',
  'Cureles Spaniel',
  'Cureles Terrier',
  'Curelesi',
  'Curelesi Hound',
  'Curelesi Mastiff',
  'Curelesi Retrieve',
  'Curelesi Retriever',
  'Curelesi Setter',
  'Curelesi Spaniel',
  'Curelesi Terrier',
  'Curelesia',
  'Curelen',
  'Curelene',
  'Curelenes',
  'Curelenes Hound',
  'Curelexi',
  'Curelexi Hound',
  'Curelexi Mastiff',
  'Curelexii',
  'Curelexii Hound',
  'Curelexii Mastiff',
  'Curelexii Retrieve',
  'Curelexii Retriever',
  'Curelexii Setter',
  'Curelexii Spaniel',
  'Curelexii Terrier',
  'Curelexia',
  'Curelexian',
  'Curelia',
  'Curelian',
  'Curelias',
  'Curelians',
  'Cureliba',
  'Curelibas',
  'Curelic',
  'Curelica',
  'Curelican',
  'Curelicas',
  'Curelicans',
  'Curelice',
  'Cureligia',
  'Cureligian',
  'Cureligias',
  'Cureligians',
  'Curelii',
  'Curelian',
  'Curelians',
  'Curelic',
  'Curelica',
  'Curelican',
  'Curelicas',
  'Curelical',
  'Curelicans',
  'Curelicos',
  'Curelicoss',
  'Curelics',
  'Curelicos',
  'Curelics',
  'Curelia',
  'Cureliae',
  'Curelian',
  'Curelians',
  'Curelias',
  'Curelidal',
  'Curelidae',
  'Curelido',
  'Curelidos',
  'Curelida',
  'Curelidas',
  'Curelidae',
  'Curelidae Mastiff',
  'Curelidae Retrieve',
  'Curelidae Retriever',
  'Curelidae Setter',
  'Curelidae Spaniel',
  'Curelidae Terrier',
  'Curelicus',
  'Curelici',
  'Curelicia',
  'Curelician',
  'Curelicia',
  'Curelician',
  'Curelicas',
  'Curelicans',
  'Curelidad',
  'Curelicade',
  'Curelicide',
  'Curelicide Mastiff',
  'Curelicide Retrieve',
  'Curelicide Retriever',
  'Curelicide Setter',
  'Curelicide Spaniel',
  'Curelicide Terrier',
  'Cureld',
  'Curelda',
  'Cureldae',
  'Cureldane',
  'Cureldanes',
  'Cureldians',
  'Cureldica',
  'Cureldican',
  'Cureldicas',
  'Cureldidus',
  'Cureldimus',
  'Cureldina',
  'Cureldinas',
  'Cureldinus',
  'Cureldinus Hound',
  'Cureldinus Mastiff',
  'Cureldinus Retrieve',
  'Cureldinus Retriever',
  'Cureldinus Setter',
  'Cureldinus Spaniel',
  'Cureldinus Terrier',
  'Mixed Breed',
];
