// File generated by flutterfire_cli.
// DO NOT EDIT, instead edit the firebase.json file in the root directory,
// then run flutterfire configure to regenerate this file.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
  show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKhsCd83vFFSGKQo3_nH5hiAS5Uyim7Ig',
    appId: '1:27966798255:web:9359cf4b7d9ed1a216575a',
    messagingSenderId: '27966798255',
    projectId: 'pawsense-8e8a3',
    authDomain: 'pawsense-8e8a3.firebaseapp.com',
    storageBucket: 'pawsense-8e8a3.firebasestorage.app',
    measurementId: 'G-EWLP8G6JR0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8Cr7cBH-2016QrA9IjspNr3dk4Zt0Z9E',
    appId: '1:27966798255:android:43cc63ff8bb5a8d116575a',
    messagingSenderId: '27966798255',
    projectId: 'pawsense-8e8a3',
    storageBucket: 'pawsense-8e8a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRpfgD3LvZLEjYBcirXbwUszwe1rzx5GM',
    appId: '1:27966798255:ios:cd8202465d7e81de16575a',
    messagingSenderId: '27966798255',
    projectId: 'pawsense-8e8a3',
    storageBucket: 'pawsense-8e8a3.firebasestorage.app',
    iosBundleId: 'com.example.pawsense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRpfgD3LvZLEjYBcirXbwUszwe1rzx5GM',
    appId: '1:27966798255:ios:cd8202465d7e81de16575a',
    messagingSenderId: '27966798255',
    projectId: 'pawsense-8e8a3',
    storageBucket: 'pawsense-8e8a3.firebasestorage.app',
    iosBundleId: 'com.example.pawsense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKhsCd83vFFSGKQo3_nH5hiAS5Uyim7Ig',
    appId: '1:27966798255:web:ef3fa30ab9b18fdf16575a',
    messagingSenderId: '27966798255',
    projectId: 'pawsense-8e8a3',
    authDomain: 'pawsense-8e8a3.firebaseapp.com',
    storageBucket: 'pawsense-8e8a3.firebasestorage.app',
    measurementId: 'G-4QBKVCTJNZ',
  );

}